---
- hosts: all
  become: yes
  gather_facts: True
 


  vars_prompt:
    - name: username
      prompt: "enter username"
      private: no  
    - name: keyfile
      prompt: "enter pub keys filename"
      private: no

  vars_files:
   - "{{keyfile}}"
 
  roles:
    - add_user
    - add_sudo_nopass
    - auth_ssh_key
