---
- hosts: all
  become: yes
  gather_facts: True

  vars_prompt:
    - name: username
      prompt: "enter username"
      private: no  
    - name: keyfile
      promt: "enter key filename"
      private: no

 
  roles:
    - add_user
    - add_sudo_nopass
  tasks:

  - name: pubkey
    authorized_key: user={{ username }} 
                    key={{ item }}
    with_items:
     - /home/prizrak83/ansible/key1

